"""
FormatForge AI — Report Schemas
Compliance reports, citation reports, and change logs.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


# ── Severity / Status ────────────────────────────────────────

class Severity(str, Enum):
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"


class ChangeStatus(str, Enum):
    APPLIED = "applied"
    SKIPPED = "skipped"
    FAILED = "failed"


# ── Individual change record ─────────────────────────────────

class ChangeRecord(BaseModel):
    """A single formatting change applied to the document."""
    element_id: str = ""
    category: str = ""  # "page_layout", "typography", "headings", etc.
    description: str = ""  # Human-readable: "Font changed from Calibri 11pt to TNR 12pt"
    old_value: Optional[str] = None
    new_value: Optional[str] = None
    rule_reference: Optional[str] = None  # e.g. "APA 7 §2.19"
    status: ChangeStatus = ChangeStatus.APPLIED
    severity: Severity = Severity.INFO


# ── Category score ────────────────────────────────────────────

class CategoryScore(BaseModel):
    """Score for a single compliance category."""
    category: str = ""
    score: float = 0.0  # 0.0 – 100.0
    max_score: float = 100.0
    weight: float = 0.0  # category weight (e.g. 0.15 for 15%)
    checks_passed: int = 0
    checks_total: int = 0
    issues: list[str] = Field(default_factory=list)


# ── Compliance report ────────────────────────────────────────

class ComplianceReport(BaseModel):
    """
    Full compliance report for a formatted document.
    Generated by the Validator agent.
    """
    style_name: str = ""
    overall_score: float = 0.0  # 0.0 – 100.0
    categories: list[CategoryScore] = Field(default_factory=list)
    changes: list[ChangeRecord] = Field(default_factory=list)
    total_changes: int = 0
    warnings: list[str] = Field(default_factory=list)
    errors: list[str] = Field(default_factory=list)
    generated_at: datetime = Field(default_factory=datetime.utcnow)

    @property
    def changes_applied(self) -> int:
        return sum(1 for c in self.changes if c.status == ChangeStatus.APPLIED)

    def add_change(self, change: ChangeRecord) -> None:
        self.changes.append(change)
        self.total_changes = len(self.changes)

    def compute_overall_score(self) -> None:
        """Compute weighted overall score from category scores."""
        if not self.categories:
            self.overall_score = 0.0
            return
        weighted = sum(cat.score * cat.weight for cat in self.categories)
        total_weight = sum(cat.weight for cat in self.categories)
        self.overall_score = round(weighted / total_weight, 1) if total_weight else 0.0


# ── Citation match ────────────────────────────────────────────

class CitationMatch(BaseModel):
    citation_text: str = ""
    matched_reference: Optional[str] = None
    location: str = ""  # e.g. "paragraph 12"
    status: str = "matched"  # "matched" | "orphan" | "ambiguous"
    issue: Optional[str] = None


class OrphanReference(BaseModel):
    reference_text: str = ""
    issue: str = "Not cited anywhere in text"


class CitationFormatIssue(BaseModel):
    citation_text: str = ""
    location: str = ""
    issue: str = ""  # e.g. "Should use '&' in parenthetical"


# ── Citation report ──────────────────────────────────────────

class CitationReport(BaseModel):
    """
    Citation consistency report.
    Generated by the Citation Engine agent.
    """
    total_citations: int = 0
    total_references: int = 0
    matched: int = 0
    orphan_citations: list[CitationMatch] = Field(default_factory=list)
    uncited_references: list[OrphanReference] = Field(default_factory=list)
    format_issues: list[CitationFormatIssue] = Field(default_factory=list)
    consistency_score: float = 0.0  # 0.0 – 100.0
    formatted_bibliography: list[str] = Field(default_factory=list)  # citeproc-py output

    def compute_score(self) -> None:
        total = self.total_citations + self.total_references
        if total == 0:
            self.consistency_score = 100.0
            return
        issues = len(self.orphan_citations) + len(self.uncited_references) + len(self.format_issues)
        self.consistency_score = round(max(0, (1 - issues / total)) * 100, 1)


# ── Pipeline result (wraps everything) ───────────────────────

class FormatResult(BaseModel):
    """
    Complete result from the formatting pipeline.
    Returned to the UI / API caller.
    """
    success: bool = True
    output_filename: Optional[str] = None
    compliance_report: ComplianceReport = Field(default_factory=ComplianceReport)
    citation_report: CitationReport = Field(default_factory=CitationReport)
    structure_summary: dict = Field(default_factory=dict)  # role → count
    processing_time_seconds: float = 0.0
    error_message: Optional[str] = None
